### ISSUE TITLE
Interaction with YeOldeTanks crashes

### ISSUE THREAD

**Issue by founderio** [Team-IO/taam#217]
https://unascribed.com/f/6daf8125_crash-2016-07-01_15.08.23-client.txt

Key Part:
```
java.lang.NullPointerException: Unexpected error
	at net.shadowfacts.shadowmc.capability.CapHelper.getCapability(CapHelper.java:42)
	at net.shadowfacts.shadowmc.tileentity.BaseTileEntity.getCapability(BaseTileEntity.java:46)
	at net.shadowfacts.yeoldetanks.block.barrel.TileEntityBarrel.getCapability(TileEntityBarrel.java:79)
	at net.teamio.taam.conveyors.ConveyorUtil.getSlots(ConveyorUtil.java:396)
	at net.teamio.taam.rendering.TaamRenderer.onDrawBlockHighlight(TaamRenderer.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_767_TaamRenderer_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:139)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1330)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1039)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by founderio** [comment]
Probably fixed with shadowfacts/ShadowMC@6c50a364fbec7bc4df3cdb0ba1cb4b5c089c0c6e - but I will create additional handlers to prevent crashing.
