### ISSUE TITLE
java.lang.NoSuchFieldError: down

### ISSUE THREAD

**Issue by founderio** [Team-IO/taam#228]
```
[12:53:07] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: down
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
        at com.surgeplay.reschedule.Reschedule.runScheduler(Reschedule.java:21) [Reschedule.class:?]
        at net.minecraft.server.MinecraftServer.func_184107_a(MinecraftServer.java:569) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:436) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: down
        at net.teamio.taam.conveyors.appliances.ApplianceAligner.<init>(ApplianceAligner.java:35) ~[ApplianceAligner.class:?]
        at net.teamio.taam.content.conveyors.BlockProductionLineAppliance.createTileEntity(BlockProductionLineAppliance.java:100) ~[BlockProductionLineAppliance.class:?]
        at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:764) ~[asf.class:?]
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:782) ~[asf.class:?]
        at net.minecraft.world.World.func_175625_s(World.java:2389) ~[aht.class:?]
        at mcjty.rftools.blocks.screens.ScreenControllerTileEntity.scan(ScreenControllerTileEntity.java:326) ~[ScreenControllerTileEntity.class:?]
        at mcjty.rftools.blocks.screens.ScreenControllerTileEntity.execute(ScreenControllerTileEntity.java:364) ~[ScreenControllerTileEntity.class:?]
        at mcjty.lib.network.PacketServerCommand$Handler.handle(PacketServerCommand.java:58) ~[PacketServerCommand$Handler.class:?]
        at mcjty.lib.network.PacketServerCommand$Handler.lambda$onMessage$0(PacketServerCommand.java:37) ~[PacketServerCommand$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 7 more
```

**Comment by founderio** [comment]
Fixed in Dev branch, will be in the next version.
