### ISSUE TITLE
NPE breaking pipes

### ISSUE THREAD

**Issue by purpleposeidon** [Team-IO/taam#254]
```
java.lang.NullPointerException: Ticking block entity
	at net.teamio.taam.piping.PipeUtil.processPipes(PipeUtil.java:190)
	at net.teamio.taam.content.piping.MachinePipe.update(MachinePipe.java:212)
	at net.teamio.taam.machines.MachineMultipart.func_73660_a(MachineMultipart.java:317)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
```
The pipe was broken in creative. I've broken plenty of pipes before; dunno why that pipe in particular decided to crash.

On Taam-1.10.2-1.1.0-beta14.jar
Rest of log: https://paste.ee/p/vI4uR

**Comment by founderio** [comment]
Could be a sync issue. That piece of code is responsible for fluid transfer between pipes.
I'll add a few null-checks to safeguard.
